server:
  port: 8889
# Sa-Token配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: simple-uuid
  # 是否输出操作日志
  is-log: true
  # 是否尝试从 cookie 里读取 Token，此值为 false 后，StpUtil.login(id) 登录时也不会再往前端注入Cookie
  isReadCookie: false
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # 根据自己设置的密码决定
    timeout: 6000
    # 操作0号数据库，默认有16个数据库
    database: 0
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
#localhost:3306/managetest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.56.181.180:3306/managetest?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      # 连接池配置
      # 配置初始化大小、最小、最大
      initial-size: 1
      min-idle: 1
      max-active: 10
      # 配置获取连接等待超时的时间
      max-wait: 3000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall,slf4j

# desktop配置
desktop:
  getAppModelById: http://localhost:8084/data/app?appId={appId}
  getApps: http://localhost:8084/data/apps
  addMemberAppModel: http://localhost:8084/data/memberApp
  addMemberModel: http://localhost:8084/data/member
  updateMemberByUserName: http://localhost:8084/data/updateMember
  modifyRoleApp: http://localhost:8084/data/modifyRoleApp
  updateMemberName: http://localhost:8084/data/updateMemberName

#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: isDelete #默认deleted
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      id-type: auto